baseURL = 'https://duanzy47.github.io/'
languageCode = 'en-us'
title = 'Maison Hatoyama'
theme = "PaperMod"
disqusShortname = "julian-10"

[params]
  description = "A retro Windows 98 style blog exploring history, culture, and ideas"
  disableSpecial1stPost = true
  ShowToc = false
  ShowPostNavLinks = true
  ShowShareButtons = false
  hideMeta = false
  ShowBreadCrumbs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

