baseURL = 'https://duanzy47.github.io/'
languageCode = 'en-us'
title = 'Maison Hatoyama'
theme = "PaperMod"
disqusShortname = "julian-10"

[params]
  disableSpecial1stPost = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

